### GET ALL ITEMS
GET http://localhost:3000/groceries/item

### GET ITEMS BY CATEGORY
GET http://localhost:3000/groceries/item/Meat

### POST NEW ITEM
POST http://localhost:3000/groceries/item HTTP/1.1
content-type: application/json

{
    "category": "Dairy",
    "itemDescription": "sour cream",
    "price": "2.11"
}

### UPDATE ITEM BY ID
PUT http://localhost:3000/groceries/item/6695d1aa9c72ca5818cfb907 HTTP/1.1
content-type: application/json

{
    "category": "Fruit",
    "itemDescription": "Apple",
    "price": "1.20"
}